[build]
  command = "npm run build"
  publish = "dist"
  
[build.environment]
  NPM_FLAGS = "--legacy-peer-deps"

[build.lifecycle]
  # Use the custom install command with the flag
  install = "npm install --legacy-peer-deps"
